### ISSUE TITLE
Could not find com.hypertrack:hypertrack:4.5.2

### ISSUE THREAD

**Issue by gulsher7** [hypertrack/sdk-react-native#12]
I'm facing  issue when i install this package in my react native project..Please reply as soon as possible..i'm working on client project..below i attached screen-short where i configured this package

![Screenshot 2020-10-01 at 1 17 30 PM](https://user-images.githubusercontent.com/56266123/94782477-e8534780-03e8-11eb-8263-2e17d363d77d.png)

**Comment by deniszpua** [comment]
Hey @gulsher7!
We keep the sdk in S3 bucket so you need to ensure you have our repository added to `repositories` block in either _:hypertrack-sdk-react-native_ module or to global android repositories, like in our [quickstart](https://github.com/hypertrack/quickstart-react-native/blob/b93951d37bb5c7aa1d528920bca40f7289e5dd93/android/build.gradle#L25).
LMK if this helpful.

**Comment by gulsher7** [comment]
> Hey @gulsher7!
> We keep the sdk in S3 bucket so you need to ensure you have our repository added to `repositories` block in either _:hypertrack-sdk-react-native_ module or to global android repositories, like in our [quickstart](https://github.com/hypertrack/quickstart-react-native/blob/b93951d37bb5c7aa1d528920bca40f7289e5dd93/android/build.gradle#L25).
> `http://m2.hypertrack.com` is an alias, in case your VPN obscures non-secure traffic, you can use `https://s3-us-west-2.amazonaws.com/m2.hypertrack.com/` instead.
> LMK if this helpful.

Sorry for late info.... Yes its helpful and resolved issue...thank you so much for your quick response.
