### ISSUE TITLE
Podspec file missing

### ISSUE THREAD

**Issue by vinaygoyal20** [hypertrack/sdk-react-native#14]
unable to install for ios because podspec file is missing

**Comment by vinaygoyal20** [comment]
Update if i download this lib as zip then it's available but i download it as an npm package its not available

**Comment by DmitryShapovalov** [comment]
@vinaygoyal20 Hello
Thanks, I am working on fix for this issue, I will notify you when a new release with fix will available.

**Comment by DmitryShapovalov** [comment]
@vinaygoyal20 That was fixed in new release `7.0.1`.
