### ISSUE TITLE
CocoaPods could not find compatible versions for pod "HyperTrack/Objective-C"

### ISSUE THREAD

**Issue by gulsher7** [hypertrack/sdk-react-native#17]
this package working fine in android but in ios dosen't ...i'm tired to facing new issues.. if one issue fixed then another issues come..Please check this sdk with latest react native version...and can you explain why hyperTrack pods not installed..? 

![Screenshot 2020-10-10 at 1 49 54 AM](https://user-images.githubusercontent.com/56266123/95629095-e5b5b980-0a9c-11eb-9154-d998ff0dabcc.png)

**Comment by tulushev** [comment]
@gulsher7 I can see the package in https://cocoapods.org/pods/HyperTrack
Can you try `pod install --repo-update`?

**Comment by gulsher7** [comment]
> @gulsher7 I can see the package in https://cocoapods.org/pods/HyperTrack
> Can you try `pod install --repo-update`?

not yet let me check

**Comment by gulsher7** [comment]
> @gulsher7 I can see the package in https://cocoapods.org/pods/HyperTrack
> Can you try `pod install --repo-update`?

thanks its worked...and thank you for your quick response...now i can sleep peacefully..
