### ISSUE TITLE
No working on Android

### ISSUE THREAD

**Issue by zainmusani** [hypertrack/sdk-react-native#2]
What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
  > Could not find com.hypertrack:hypertrack:3.1.2.
    Searched in the following locations:
      - file:/Users/macbookpro/.m2/repository/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.pom
      - file:/Users/macbookpro/.m2/repository/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.aar
      - https://dl.google.com/dl/android/maven2/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.pom
      - https://dl.google.com/dl/android/maven2/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.aar
      - https://jcenter.bintray.com/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.pom
      - https://jcenter.bintray.com/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.aar
      - file:/Users/macbookpro/Documents/ReactNative/HypertrackTest/node_modules/react-native/android/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.pom
      - file:/Users/macbookpro/Documents/ReactNative/HypertrackTest/node_modules/react-native/android/com/hypertrack/hypertrack/3.1.2/hypertrack-3.1.2.aar
    Required by:
        project :app > project :hypertrack-sdk-react-native`

**Comment by tulushev** [comment]
Hey @zainmusani we added our maven SDK repo to the [integration instructions](https://github.com/hypertrack/sdk-react-native#add-maven-for-google-play-service-libraries). Should work now.
