### ISSUE TITLE
Not issue just some queries

### ISSUE THREAD

**Issue by reactProjects7** [hypertrack/sdk-react-native#24]
Sorry for the raised unnecessary issue, i have one question can we use hypertrack map in react native app i don't want use react-native-maps library.  I want fully tracking by hypertrack not by custom map.

**Comment by deniszpua** [comment]
Hi @reactProjects7.
You can use the webview to display the tracking page from `views.share_url` property of [trips](https://hypertrack.com/docs/references#references-apis-trips-get-trips) or [devices](https://hypertrack.com/docs/references#references-apis-devices-get-device-list).
BTW, you can ask questions on our [Slack Support Channel](https://join.slack.com/t/hypertracksupport/shared_invite/enQtNDA0MDYxMzY1MDMxLTdmNDQ1ZDA1MTQxOTU2NTgwZTNiMzUyZDk0OThlMmJkNmE0ZGI2NGY2ZGRhYjY0Yzc0NTJlZWY2ZmE5ZTA2NjI) to get the feedback faster.
