### ISSUE TITLE
Autolinking for react-native >= 0.60

### ISSUE THREAD

**Issue by divyanshu013** [hypertrack/sdk-react-native#5]
Hi, is it possible to autolink for RN > 0.60?

**Comment by tulushev** [comment]
Hi @divyanshu013 we are planning to add autolinking with our 0.60+ update. Will update here in this issue when it happens

**Comment by ammarhaider7** [comment]
@tulushev Any idea when this might be coming? I'll just downgrade my app to 0.59 if this isn't a priority..

**Comment by tulushev** [comment]
@ammarhaider7 we are planning to update this or next week

**Comment by ammarhaider7** [comment]
> @ammarhaider7 we are planning to update this or next week

Hey @tulushev any update?

**Comment by DmitryShapovalov** [comment]
@ammarhaider7  Hello, the new release 7.0.1 of HyperTrack React-Native wrapper now available for use. That release includes react-native 0.63.3 supports.
