### ISSUE TITLE
Use of undeclared identifier 'HTSDK'

### ISSUE THREAD

**Issue by saivyas** [hypertrack/sdk-react-native#6]
I don't know but getting errors like `Use of undeclared identifier 'HTSDK' ` in Xcode Ios. I followed each step mentioned in document.

Please Help me If I did anything wrong 

![image](https://user-images.githubusercontent.com/23031470/71425026-487cc680-26be-11ea-97c5-5b1686eb54eb.png)

**Comment by tulushev** [comment]
@saivyas this can happen for multiple reasons:
* You opened the `.xcproject` instead of `.xcworkspace`
* The SDK wasn't installed properly with CocoaPods. Check the `Podfile.lock` file for the specific HTSDK version installed. Try version 3.7.0.
* Try cleaning and building again

**Comment by tulushev** [comment]
@saivyas I've updated the SDK to 6.2.1, this should fix your issue.

If you want to update your Quickstart/project manually, just update the RN SDK package to 6.2.1, update Podfile to look like this:

```ruby
platform :ios, '11.0'

target 'Quickstart' do
  use_frameworks!
  pod 'HyperTrack/Objective-C', '4.0.1'
end
```

and then `pod update`, clean and build.
